version : '3.1'

services:
    web:
        build:
            context: ./front
            dockerfile: DockerFile
        ports:
        - "3000:3000"

    api:
        build:
            context: ./back
            dockerfile: DockerFile
        ports:
        - "3001:3001"
        
